version: "3.4"
services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    network_mode: "bridge"
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
    volumes:
      - /home/fran/lidarr/config:/config
      - /home/fran/lidarr/downloads:/downloads
      - ${FRAN_MEDIA}:/FranMedia/
    ports:
      - 8686:8686
    restart: always