version: '3'

services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=US/Eastern
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /home/fran/overseer/config:/app/config
    restart: unless-stopped