version: "3.4"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    network_mode: "bridge"
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
    volumes:
      - /home/fran/sonarr/config:/config
      - /home/fran/sonarr/downloads:/downloads
      - ${FRAN_MEDIA}:/FranMedia/
    ports:
      - 8989:8989
    restart: always