version: "3.4"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/fran/plex/config:/config
      - ${FRAN_MUSIC}:/music
      - ${FRAN_MOVIES}:/movies
      - ${FRAN_TV}:/tvshows
    restart: unless-stopped