- hosts: "*"

  vars_files:
    - ../secret-vars.yml
    - ../dependencies-vars.yml

  become: yes
  roles:
    - geerlingguy.docker

  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: 'yes'

    - name: Install Dependencies
      apt:
        name: "{{ host_dependencies }}"
        state: latest
        update_cache: yes      

    - name: Creates directory
      file:
        path: "{{ item }}"
        state: directory
        recurse: yes

      with_items:
      - /home/fran/plex/config
      - /home/fran/minecraft/config
      - /home/fran/minecraft-ftb/config      
      - /home/fran/tdarr/config
      - /home/fran/tautulli/config
      - /home/fran/sonarr/config
      - /home/fran/sabnzbd/config
      - /home/fran/radarr/config
      - /home/fran/lidarr/config
      - /home/fran/jellyfin/config
      - /home/fran/jackett/config
      - /home/fran/heimdall/config
      - /home/fran/portainer/config
      - /home/fran/wireguard/config   
      - /home/fran/wireguard/lib/modules 
      - /home/fran/duckdns/config   
      - /home/fran/youtubedl/config      
      - /home/fran/photoprism_fran/config      
      - /home/fran/photoprism_family/config      
      - /home/fran/overseer/config   

    - name: mount FranMedia
      mount:
        state: "mounted"
        fstype: "cifs"
        name: "/mnt/FranMedia"
        src: "{{ nas_mount_src }}"
        opts: "{{ nas_mount_opts }}"

    - name: mount FranHomeMedia
      mount:
        state: "mounted"
        fstype: "cifs"
        name: "/mnt/FranHomeMedia"
        src: "{{ nas_mount_src_home }}"
        opts: "{{ nas_mount_opts }}"

 
    - name: copy docker-compose files
      copy: src={{ item.src }} dest={{ item.dest }}
      with_items:
         - { src: "{{ playbook_dir }}/docker-compose/.env", dest: '/home/fran/.env' } 
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-heimdall.yml", dest: '/home/fran/heimdall/docker-compose.yml' }         
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-jackett.yml", dest: '/home/fran/jackett/docker-compose.yml' }
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-jellyfin.yml", dest: '/home/fran/jellyfin/docker-compose.yml' }
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-radarr.yml", dest: '/home/fran/radarr/docker-compose.yml' }
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-plex.yml", dest: '/home/fran/plex/docker-compose.yml' }
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-tdarr.yml", dest: '/home/fran/tdarr/docker-compose.yml' }
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-minecraft.yml", dest: '/home/fran/minecraft/docker-compose.yml' }  
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-minecraft-ftb.yml", dest: '/home/fran/minecraft-ftb/docker-compose.yml' }                 
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-sabnzbd.yml", dest: '/home/fran/sabnzbd/docker-compose.yml' }
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-tautulli.yml", dest: '/home/fran/tautulli/docker-compose.yml' }
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-radarr.yml", dest: '/home/fran/radarr/docker-compose.yml' }
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-lidarr.yml", dest: '/home/fran/lidarr/docker-compose.yml' }
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-sonarr.yml", dest: '/home/fran/sonarr/docker-compose.yml' }
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-duckdns.yml", dest: '/home/fran/duckdns/docker-compose.yml' }
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-wireguard.yml", dest: '/home/fran/wireguard/docker-compose.yml' }
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-portainer.yml", dest: '/home/fran/portainer/docker-compose.yml' }
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-portainer.yml", dest: '/home/fran/portainer/docker-compose.yml' }    
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-youtubedl.yml", dest: '/home/fran/youtubedl/docker-compose.yml' }
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-photoprism-fran.yml", dest: '/home/fran/photoprism_fran/docker-compose.yml' }   
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-photoprism-family.yml", dest: '/home/fran/photoprism_family/docker-compose.yml' }             
         - { src: "{{ playbook_dir }}/docker-compose/docker-compose-overseer.yml", dest: '/home/fran/overseer/docker-compose.yml' }    
         - { src: "{{ playbook_dir }}/update_docker_containers.sh", dest: '/home/fran/update_docker_containers.sh'  }  

    - name: Changing perm of "update_docker_containers.sh", adding "+x"
      file: dest=/home/fran/update_docker_containers.sh mode=a+x      

    - name: run dos2unix on update_docker_container.sh script incase script was modified in windows
      command: dos2unix -k -o /home/fran/update_docker_containers.sh 

    - name: Execute update_docker_containers.sh
      command: sh /home/fran/update_docker_containers.sh  
